// GENERATED BY custom script
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart' as intl;

abstract class AppLocalizations {
  AppLocalizations(this.localeName);

  final String localeName;

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates = <LocalizationsDelegate<dynamic>>[
    delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
  ];

  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('es'),
  ];
  String get appTitle;
  String get homeHeaderTitle;
  String get homeQuickAccessGymLeaders;
  String get homeQuickAccessNatures;
  String get homeQuickAccessMatchups;
  String get homeQuickAccessEvolutionChains;
  String get homeQuickAccessBreeding;
  String get homeQuickAccessBerries;
  String get authLoginTitle;
  String get authLoginSubtitle;
  String get authEmailLabel;
  String get authEmailHint;
  String get authPasswordLabel;
  String get authLoginButton;
  String get authNoAccountCta;
  String get authLoginError;
  String get authEmailRequired;
  String get authEmailInvalid;
  String get authPasswordRequired;
  String get authPasswordLength;
  String get authRegisterTitle;
  String get authRegisterSubtitle;
  String get authCreateAccountButton;
  String get authAlreadyHaveAccountCta;
  String get authRegisterError;
  String get authSecurePasswordRequired;
  String get authPasswordStrongSuggestion;
  String get authConfirmPasswordLabel;
  String get authPasswordsMismatch;
  String get authSnackbarNoUser;
  String get authProfileUpdated;
  String get authProfileUpdateError;
  String get authUpdateInfoTitle;
  String get authUpdateInfoSubtitle;
  String get authNewPasswordOptionalLabel;
  String get settingsTitle;
  String get settingsAccountSection;
  String get settingsNoEmail;
  String get settingsEditProfile;
  String get settingsSignOut;
  String get settingsAppearanceSection;
  String get settingsLanguageSection;
  String get settingsLanguageLabel;
  String get settingsLanguageEnglish;
  String get settingsLanguageSpanish;
  String get settingsLightModeTitle;
  String get settingsLightModeSubtitle;
  String get settingsDarkModeTitle;
  String get settingsDarkModeSubtitle;
  String get settingsInfo;
  String get settingsSaveChanges;
  String get favoritesDefaultTitle;
  String get favoritesEmptyTitle;
  String get favoritesEmptySubtitle;
  String get homeQuickAccessTitle;
  String get homeSectionPokedexTitle;
  String get homeSectionPokedexSubtitle;
  String get homeSectionFavoritesTitle;
  String get homeSectionFavoritesSubtitle;
  String get homeSectionMovesTitle;
  String get homeSectionMovesSubtitle;
  String get homeSectionTmTitle;
  String get homeSectionTmSubtitle;
  String get homeSectionAbilitiesTitle;
  String get homeSectionAbilitiesSubtitle;
  String get homeSectionChecklistsTitle;
  String get homeSectionChecklistsSubtitle;
  String get homeSectionPartiesTitle;
  String get homeSectionPartiesSubtitle;
  String get homeSectionLocationsTitle;
  String get homeSectionLocationsSubtitle;
  String homePlaceholderMessage({required String sectionName});
  String get abilitiesDefaultTitle;
  String get abilitiesSearchHint;
  String get abilitiesErrorMessage;
  String get commonRetry;
  String get abilitiesEmptySearch;
  String get abilitiesEmptyGeneral;
  String get abilitiesNoDescription;
  String get abilitiesNoShortDescription;
  String get abilitiesFullDescriptionTitle;
  String get abilitiesFullDescriptionFallback;
  String get abilitiesPokemonSectionTitle;
  String get abilitiesPokemonEmpty;
  String get abilitiesPokemonErrorTitle;
  String get abilitiesPokemonErrorDescription;
  String get pokedexSortNumberLabel;
  String get pokedexSortNameLabel;
  String get pokedexSortHeightLabel;
  String get pokedexSortWeightLabel;
  String get pokedexSearchHint;
  String get pokedexFiltersTooltip;
  String get pokedexOfflineNoCache;
  String get pokedexOfflineBanner;
  String get pokedexConnectionRestored;
  String get pokedexLoadError;
  String get pokedexOfflineFiltersLimited;
  String pokedexShowingCountSimple({required int count});
  String pokedexShowingCountWithTotal({required int count, required int total});
  String pokedexActiveFilters(int count);
  String get pokedexSortDirectionAscending;
  String get pokedexSortDirectionDescending;
  String pokedexFilterSummarySearch({required String query});
  String pokedexFilterSummaryType({required String value});
  String pokedexFilterSummaryGeneration({required String value});
  String pokedexFilterSummaryRegion({required String value});
  String pokedexFilterSummaryShape({required String value});
  String pokedexFilterSummarySort({required String value});
  String get pokedexNoResults;
  String get pokedexFiltersTitle;
  String get pokedexFiltersCloseTooltip;
  String get pokedexFilterSectionTypes;
  String get pokedexFilterSectionGenerations;
  String get pokedexFilterSectionRegions;
  String get pokedexFilterSectionShapes;
  String get pokedexFilterEmptyTypes;
  String get pokedexFilterEmptyGenerations;
  String get pokedexFilterEmptyRegions;
  String get pokedexFilterEmptyShapes;
  String get pokedexFiltersClear;
  String get commonCancel;
  String get commonApply;
  String get pokedexSortSheetTitle;
  String get pokedexSortCriteriaLabel;
  String get pokedexSortDirectionLabel;
  String get pokedexSortAscendingShort;
  String get pokedexSortDescendingShort;
  String get favoritesRemoveAction;
  String get favoritesAddAction;
}
class AppLocalizationsEN extends AppLocalizations {
  AppLocalizationsEN(): super('en');
  @override
  String get appTitle => 'Pokédex GraphQL';
  @override
  String get homeHeaderTitle => 'ProDex';
  @override
  String get homeQuickAccessGymLeaders => 'Gym Leaders & Elite 4';
  @override
  String get homeQuickAccessNatures => 'Natures';
  @override
  String get homeQuickAccessMatchups => 'Type Matchups';
  @override
  String get homeQuickAccessEvolutionChains => 'Evolution Chains';
  @override
  String get homeQuickAccessBreeding => 'Breeding Guides';
  @override
  String get homeQuickAccessBerries => 'Berry Farming';
  @override
  String get authLoginTitle => 'Welcome back';
  @override
  String get authLoginSubtitle => 'Sign in with your email to access your Pokédex.';
  @override
  String get authEmailLabel => 'Email';
  @override
  String get authEmailHint => 'ash.ketchum@poke.app';
  @override
  String get authPasswordLabel => 'Password';
  @override
  String get authLoginButton => 'Sign in';
  @override
  String get authNoAccountCta => 'Don\'t have an account? Sign up';
  @override
  String get authLoginError => 'We couldn\'t sign you in. Try again.';
  @override
  String get authEmailRequired => 'Enter your email.';
  @override
  String get authEmailInvalid => 'Invalid email format.';
  @override
  String get authPasswordRequired => 'Enter your password.';
  @override
  String get authPasswordLength => 'The password must contain at least 6 characters.';
  @override
  String get authRegisterTitle => 'Create your account';
  @override
  String get authRegisterSubtitle => 'Register to sync your teams and collections across all your devices.';
  @override
  String get authCreateAccountButton => 'Create account';
  @override
  String get authAlreadyHaveAccountCta => 'Already have an account? Sign in';
  @override
  String get authRegisterError => 'We couldn\'t create your account. Try again later.';
  @override
  String get authSecurePasswordRequired => 'Enter a secure password.';
  @override
  String get authPasswordStrongSuggestion => 'Use letters and numbers for a stronger password.';
  @override
  String get authConfirmPasswordLabel => 'Confirm password';
  @override
  String get authPasswordsMismatch => 'Passwords do not match.';
  @override
  String get authSnackbarNoUser => 'User information is not available.';
  @override
  String get authProfileUpdated => 'Profile updated successfully.';
  @override
  String get authProfileUpdateError => 'We couldn\'t update the profile.';
  @override
  String get authUpdateInfoTitle => 'Update your login information.';
  @override
  String get authUpdateInfoSubtitle => 'Change your email address or set a new password. Changes apply immediately.';
  @override
  String get authNewPasswordOptionalLabel => 'New password (optional)';
  @override
  String get settingsTitle => 'Settings';
  @override
  String get settingsAccountSection => 'Account';
  @override
  String get settingsNoEmail => 'No email on record';
  @override
  String get settingsEditProfile => 'Edit profile';
  @override
  String get settingsSignOut => 'Sign out';
  @override
  String get settingsAppearanceSection => 'Appearance';
  @override
  String get settingsLanguageSection => 'Language';
  @override
  String get settingsLanguageLabel => 'App language';
  @override
  String get settingsLanguageEnglish => 'English';
  @override
  String get settingsLanguageSpanish => 'Spanish';
  @override
  String get settingsLightModeTitle => 'Light mode';
  @override
  String get settingsLightModeSubtitle => 'Bright backgrounds for well-lit environments.';
  @override
  String get settingsDarkModeTitle => 'Dark mode';
  @override
  String get settingsDarkModeSubtitle => 'Dim the lights to reduce eye strain at night.';
  @override
  String get settingsInfo => 'Settings save immediately and affect the entire app.';
  @override
  String get settingsSaveChanges => 'Save changes';
  @override
  String get favoritesDefaultTitle => 'Favorites';
  @override
  String get favoritesEmptyTitle => 'You don\'t have favorite Pokémon yet.';
  @override
  String get favoritesEmptySubtitle => 'Explore the Pokédex and tap the heart to save your favorites.';
  @override
  String get homeQuickAccessTitle => 'Quick access';
  @override
  String get homeSectionPokedexTitle => 'Pokédex';
  @override
  String get homeSectionPokedexSubtitle => 'National index & regional dexes';
  @override
  String get homeSectionFavoritesTitle => 'Favorites';
  @override
  String get homeSectionFavoritesSubtitle => 'Your saved Pokémon';
  @override
  String get homeSectionMovesTitle => 'Moves';
  @override
  String get homeSectionMovesSubtitle => 'Damage, effects & contest data';
  @override
  String get homeSectionTmTitle => 'TM';
  @override
  String get homeSectionTmSubtitle => 'Machines & tutors by generation';
  @override
  String get homeSectionAbilitiesTitle => 'Abilities';
  @override
  String get homeSectionAbilitiesSubtitle => 'Passive effects & triggers';
  @override
  String get homeSectionChecklistsTitle => 'Checklists';
  @override
  String get homeSectionChecklistsSubtitle => 'Track goals & collections';
  @override
  String get homeSectionPartiesTitle => 'Parties';
  @override
  String get homeSectionPartiesSubtitle => 'Build teams & strategies';
  @override
  String get homeSectionLocationsTitle => 'Locations';
  @override
  String get homeSectionLocationsSubtitle => 'Regions, maps & encounter data';
  @override
  String homePlaceholderMessage({required String sectionName}) => 'The ${sectionName} section will be available soon.';
  @override
  String get abilitiesDefaultTitle => 'Abilities';
  @override
  String get abilitiesSearchHint => 'Search ability…';
  @override
  String get abilitiesErrorMessage => 'We couldn’t load the abilities.';
  @override
  String get commonRetry => 'Retry';
  @override
  String get abilitiesEmptySearch => 'We couldn’t find abilities that match your search.';
  @override
  String get abilitiesEmptyGeneral => 'No abilities are available right now.';
  @override
  String get abilitiesNoDescription => 'No description available.';
  @override
  String get abilitiesNoShortDescription => 'No short description available.';
  @override
  String get abilitiesFullDescriptionTitle => 'Full description';
  @override
  String get abilitiesFullDescriptionFallback => 'No description is available in this language.';
  @override
  String get abilitiesPokemonSectionTitle => 'Pokémon with this ability';
  @override
  String get abilitiesPokemonEmpty => 'We couldn’t find Pokémon associated with this ability.';
  @override
  String get abilitiesPokemonErrorTitle => 'We couldn’t load the associated Pokémon.';
  @override
  String get abilitiesPokemonErrorDescription => 'Try again to see which Pokémon have this ability.';
  @override
  String get pokedexSortNumberLabel => 'Number';
  @override
  String get pokedexSortNameLabel => 'Name';
  @override
  String get pokedexSortHeightLabel => 'Height';
  @override
  String get pokedexSortWeightLabel => 'Weight';
  @override
  String get pokedexSearchHint => 'Search by name or number';
  @override
  String get pokedexFiltersTooltip => 'Filters';
  @override
  String get pokedexOfflineNoCache => 'No connection and no cached data available.';
  @override
  String get pokedexOfflineBanner => 'Offline mode active. Showing cached data.';
  @override
  String get pokedexConnectionRestored => 'Connection restored.';
  @override
  String get pokedexLoadError => 'We couldn’t load the Pokédex. Try again.';
  @override
  String get pokedexOfflineFiltersLimited => 'Offline mode active. Some filters may be limited.';
  @override
  String pokedexShowingCountSimple({required int count}) => 'Showing ${count} Pokémon.';
  @override
  String pokedexShowingCountWithTotal({required int count, required int total}) => 'Showing ${count} of ${total} Pokémon.';
  @override
  String pokedexActiveFilters(int count) {
    return intl.Intl.pluralLogic(
      count,
      locale: localeName,
      one: 'count',
      other: 'count',
    );
  }
  @override
  String get pokedexSortDirectionAscending => 'ascending';
  @override
  String get pokedexSortDirectionDescending => 'descending';
  @override
  String pokedexFilterSummarySearch({required String query}) => 'Search: ${query}';
  @override
  String pokedexFilterSummaryType({required String value}) => 'Type: ${value}';
  @override
  String pokedexFilterSummaryGeneration({required String value}) => 'Generation: ${value}';
  @override
  String pokedexFilterSummaryRegion({required String value}) => 'Region: ${value}';
  @override
  String pokedexFilterSummaryShape({required String value}) => 'Form: ${value}';
  @override
  String pokedexFilterSummarySort({required String value}) => 'Sort: ${value}';
  @override
  String get pokedexNoResults => 'No Pokémon match the current filters.';
  @override
  String get pokedexFiltersTitle => 'Filters';
  @override
  String get pokedexFiltersCloseTooltip => 'Close';
  @override
  String get pokedexFilterSectionTypes => 'Types';
  @override
  String get pokedexFilterSectionGenerations => 'Generations';
  @override
  String get pokedexFilterSectionRegions => 'Regions';
  @override
  String get pokedexFilterSectionShapes => 'Shapes';
  @override
  String get pokedexFilterEmptyTypes => 'No types available right now.';
  @override
  String get pokedexFilterEmptyGenerations => 'No generations available right now.';
  @override
  String get pokedexFilterEmptyRegions => 'No regions available right now.';
  @override
  String get pokedexFilterEmptyShapes => 'No shapes available right now.';
  @override
  String get pokedexFiltersClear => 'Clear';
  @override
  String get commonCancel => 'Cancel';
  @override
  String get commonApply => 'Apply';
  @override
  String get pokedexSortSheetTitle => 'Sort by';
  @override
  String get pokedexSortCriteriaLabel => 'Criterion';
  @override
  String get pokedexSortDirectionLabel => 'Direction';
  @override
  String get pokedexSortAscendingShort => 'Asc';
  @override
  String get pokedexSortDescendingShort => 'Desc';
  @override
  String get favoritesRemoveAction => 'Remove from favorites';
  @override
  String get favoritesAddAction => 'Add to favorites';
}

class AppLocalizationsES extends AppLocalizations {
  AppLocalizationsES(): super('es');
  @override
  String get appTitle => 'Pokédex GraphQL';
  @override
  String get homeHeaderTitle => 'ProDex';
  @override
  String get homeQuickAccessGymLeaders => 'Líderes de Gimnasio y Alto Mando';
  @override
  String get homeQuickAccessNatures => 'Naturalezas';
  @override
  String get homeQuickAccessMatchups => 'Enfrentamientos de tipos';
  @override
  String get homeQuickAccessEvolutionChains => 'Cadenas evolutivas';
  @override
  String get homeQuickAccessBreeding => 'Guías de crianza';
  @override
  String get homeQuickAccessBerries => 'Cultivo de bayas';
  @override
  String get authLoginTitle => 'Bienvenido de nuevo';
  @override
  String get authLoginSubtitle => 'Inicia sesión con tu correo electrónico para acceder a tu Pokédex.';
  @override
  String get authEmailLabel => 'Correo electrónico';
  @override
  String get authEmailHint => 'ash.ketchum@poke.app';
  @override
  String get authPasswordLabel => 'Contraseña';
  @override
  String get authLoginButton => 'Iniciar sesión';
  @override
  String get authNoAccountCta => '¿No tienes cuenta? Regístrate';
  @override
  String get authLoginError => 'No fue posible iniciar sesión. Inténtalo de nuevo.';
  @override
  String get authEmailRequired => 'Ingresa tu correo electrónico.';
  @override
  String get authEmailInvalid => 'Formato de correo inválido.';
  @override
  String get authPasswordRequired => 'Ingresa tu contraseña.';
  @override
  String get authPasswordLength => 'La contraseña debe tener al menos 6 caracteres.';
  @override
  String get authRegisterTitle => 'Crea tu cuenta';
  @override
  String get authRegisterSubtitle => 'Regístrate para sincronizar tus equipos y colecciones en todos tus dispositivos.';
  @override
  String get authCreateAccountButton => 'Crear cuenta';
  @override
  String get authAlreadyHaveAccountCta => '¿Ya tienes una cuenta? Inicia sesión';
  @override
  String get authRegisterError => 'No pudimos crear tu cuenta. Inténtalo más tarde.';
  @override
  String get authSecurePasswordRequired => 'Ingresa una contraseña segura.';
  @override
  String get authPasswordStrongSuggestion => 'Usa letras y números para una contraseña más fuerte.';
  @override
  String get authConfirmPasswordLabel => 'Confirmar contraseña';
  @override
  String get authPasswordsMismatch => 'Las contraseñas no coinciden.';
  @override
  String get authSnackbarNoUser => 'No hay información de usuario disponible.';
  @override
  String get authProfileUpdated => 'Perfil actualizado correctamente.';
  @override
  String get authProfileUpdateError => 'No fue posible actualizar el perfil.';
  @override
  String get authUpdateInfoTitle => 'Actualiza tu información de acceso.';
  @override
  String get authUpdateInfoSubtitle => 'Puedes cambiar tu correo electrónico o establecer una nueva contraseña. Los cambios se aplican inmediatamente.';
  @override
  String get authNewPasswordOptionalLabel => 'Nueva contraseña (opcional)';
  @override
  String get settingsTitle => 'Configuración';
  @override
  String get settingsAccountSection => 'Cuenta';
  @override
  String get settingsNoEmail => 'Sin correo registrado';
  @override
  String get settingsEditProfile => 'Editar perfil';
  @override
  String get settingsSignOut => 'Cerrar sesión';
  @override
  String get settingsAppearanceSection => 'Apariencia';
  @override
  String get settingsLanguageSection => 'Idioma';
  @override
  String get settingsLanguageLabel => 'Idioma de la app';
  @override
  String get settingsLanguageEnglish => 'Inglés';
  @override
  String get settingsLanguageSpanish => 'Español';
  @override
  String get settingsLightModeTitle => 'Modo claro';
  @override
  String get settingsLightModeSubtitle => 'Fondos luminosos ideales para entornos bien iluminados.';
  @override
  String get settingsDarkModeTitle => 'Modo oscuro';
  @override
  String get settingsDarkModeSubtitle => 'Atenúa la luz para reducir el cansancio visual por la noche.';
  @override
  String get settingsInfo => 'La configuración se guarda inmediatamente y afecta a toda la aplicación.';
  @override
  String get settingsSaveChanges => 'Guardar cambios';
  @override
  String get favoritesDefaultTitle => 'Favoritos';
  @override
  String get favoritesEmptyTitle => 'Aún no tienes Pokémon favoritos.';
  @override
  String get favoritesEmptySubtitle => 'Explora la Pokédex y marca con el corazón los Pokémon que quieras guardar.';
  @override
  String get homeQuickAccessTitle => 'Accesos rápidos';
  @override
  String get homeSectionPokedexTitle => 'Pokédex';
  @override
  String get homeSectionPokedexSubtitle => 'Índice nacional y pokédex regionales';
  @override
  String get homeSectionFavoritesTitle => 'Favoritos';
  @override
  String get homeSectionFavoritesSubtitle => 'Tus Pokémon guardados';
  @override
  String get homeSectionMovesTitle => 'Movimientos';
  @override
  String get homeSectionMovesSubtitle => 'Daño, efectos y datos de concursos';
  @override
  String get homeSectionTmTitle => 'MT';
  @override
  String get homeSectionTmSubtitle => 'Máquinas y tutores por generación';
  @override
  String get homeSectionAbilitiesTitle => 'Habilidades';
  @override
  String get homeSectionAbilitiesSubtitle => 'Efectos pasivos y activadores';
  @override
  String get homeSectionChecklistsTitle => 'Listas de control';
  @override
  String get homeSectionChecklistsSubtitle => 'Sigue metas y colecciones';
  @override
  String get homeSectionPartiesTitle => 'Equipos';
  @override
  String get homeSectionPartiesSubtitle => 'Arma equipos y estrategias';
  @override
  String get homeSectionLocationsTitle => 'Ubicaciones';
  @override
  String get homeSectionLocationsSubtitle => 'Regiones, mapas y datos de encuentros';
  @override
  String homePlaceholderMessage({required String sectionName}) => 'La sección de ${sectionName} estará disponible pronto.';
  @override
  String get abilitiesDefaultTitle => 'Habilidades';
  @override
  String get abilitiesSearchHint => 'Buscar habilidad…';
  @override
  String get abilitiesErrorMessage => 'No se pudieron cargar las habilidades.';
  @override
  String get commonRetry => 'Reintentar';
  @override
  String get abilitiesEmptySearch => 'No encontramos habilidades que coincidan con tu búsqueda.';
  @override
  String get abilitiesEmptyGeneral => 'No hay habilidades disponibles en este momento.';
  @override
  String get abilitiesNoDescription => 'Sin descripción disponible.';
  @override
  String get abilitiesNoShortDescription => 'Sin descripción breve disponible.';
  @override
  String get abilitiesFullDescriptionTitle => 'Descripción completa';
  @override
  String get abilitiesFullDescriptionFallback => 'Sin descripción disponible en este idioma.';
  @override
  String get abilitiesPokemonSectionTitle => 'Pokémon que la poseen';
  @override
  String get abilitiesPokemonEmpty => 'No encontramos Pokémon asociados a esta habilidad.';
  @override
  String get abilitiesPokemonErrorTitle => 'No pudimos cargar los Pokémon asociados.';
  @override
  String get abilitiesPokemonErrorDescription => 'Intenta nuevamente para ver qué Pokémon cuentan con esta habilidad.';
  @override
  String get pokedexSortNumberLabel => 'Número';
  @override
  String get pokedexSortNameLabel => 'Nombre';
  @override
  String get pokedexSortHeightLabel => 'Altura';
  @override
  String get pokedexSortWeightLabel => 'Peso';
  @override
  String get pokedexSearchHint => 'Buscar por nombre o número';
  @override
  String get pokedexFiltersTooltip => 'Filtros';
  @override
  String get pokedexOfflineNoCache => 'Sin conexión y sin datos guardados localmente.';
  @override
  String get pokedexOfflineBanner => 'Modo offline activo. Mostrando datos guardados localmente.';
  @override
  String get pokedexConnectionRestored => 'Conexión restablecida.';
  @override
  String get pokedexLoadError => 'No se pudo cargar la Pokédex. Intenta nuevamente.';
  @override
  String get pokedexOfflineFiltersLimited => 'Modo offline activo. Algunos filtros pueden ser limitados.';
  @override
  String pokedexShowingCountSimple({required int count}) => 'Mostrando ${count} Pokémon.';
  @override
  String pokedexShowingCountWithTotal({required int count, required int total}) => 'Mostrando ${count} de ${total} Pokémon.';
  @override
  String pokedexActiveFilters(int count) {
    return intl.Intl.pluralLogic(
      count,
      locale: localeName,
      one: 'count',
      other: 'count',
    );
  }
  @override
  String get pokedexSortDirectionAscending => 'ascendente';
  @override
  String get pokedexSortDirectionDescending => 'descendente';
  @override
  String pokedexFilterSummarySearch({required String query}) => 'Búsqueda: ${query}';
  @override
  String pokedexFilterSummaryType({required String value}) => 'Tipo: ${value}';
  @override
  String pokedexFilterSummaryGeneration({required String value}) => 'Generación: ${value}';
  @override
  String pokedexFilterSummaryRegion({required String value}) => 'Región: ${value}';
  @override
  String pokedexFilterSummaryShape({required String value}) => 'Forma: ${value}';
  @override
  String pokedexFilterSummarySort({required String value}) => 'Orden: ${value}';
  @override
  String get pokedexNoResults => 'No se encontraron Pokémon para los filtros actuales.';
  @override
  String get pokedexFiltersTitle => 'Filtros';
  @override
  String get pokedexFiltersCloseTooltip => 'Cerrar';
  @override
  String get pokedexFilterSectionTypes => 'Tipos';
  @override
  String get pokedexFilterSectionGenerations => 'Generaciones';
  @override
  String get pokedexFilterSectionRegions => 'Regiones';
  @override
  String get pokedexFilterSectionShapes => 'Formas';
  @override
  String get pokedexFilterEmptyTypes => 'No hay tipos disponibles por ahora.';
  @override
  String get pokedexFilterEmptyGenerations => 'No hay generaciones disponibles por ahora.';
  @override
  String get pokedexFilterEmptyRegions => 'No hay regiones disponibles por ahora.';
  @override
  String get pokedexFilterEmptyShapes => 'No hay formas disponibles por ahora.';
  @override
  String get pokedexFiltersClear => 'Limpiar';
  @override
  String get commonCancel => 'Cancelar';
  @override
  String get commonApply => 'Aplicar';
  @override
  String get pokedexSortSheetTitle => 'Ordenar por';
  @override
  String get pokedexSortCriteriaLabel => 'Criterio';
  @override
  String get pokedexSortDirectionLabel => 'Dirección';
  @override
  String get pokedexSortAscendingShort => 'Asc';
  @override
  String get pokedexSortDescendingShort => 'Desc';
  @override
  String get favoritesRemoveAction => 'Quitar de favoritos';
  @override
  String get favoritesAddAction => 'Agregar a favoritos';
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => <String>['en', 'es'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    switch (locale.languageCode) {
      case 'es':
        return SynchronousFuture<AppLocalizations>(AppLocalizationsES());
      case 'en':
      default:
        return SynchronousFuture<AppLocalizations>(AppLocalizationsEN());
    }
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
